// Frontend type aliases for backend schemas.
//
// These re-export from api-types.ts (generated by `make generate-client`
// from the FastAPI OpenAPI spec) so request/response shapes stay in sync
// with the backend's Pydantic models. Add a new line here whenever you
// need to reference a backend schema from frontend code.

import type { components } from "./api-types";

export type Submission = components["schemas"]["SubmissionResponse"];
export type SubmissionCreate = components["schemas"]["SubmissionCreate"];
export type SubmissionUpdate = components["schemas"]["SubmissionUpdate"];
export type SubmissionStatus = components["schemas"]["SubmissionStatus"];
export type User = components["schemas"]["UserResponse"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
